In [1]:
import numpy as np 

In [5]:
array_uni = np.array([1,3,5,7,9,11,50])
print("Shape:", array_uni.shape)
print("Array_unidades:",array_uni )

Shape: (7,)
Array_unidades: [ 1  3  5  7  9 11 50]


In [7]:
array_uni[4]

9

In [9]:
array_uni[2:4]

array([5, 7])

In [13]:
array_uni[0:3]

array([1, 3, 5])

In [17]:
# Crear una array de dos dimensiones 
array_multidimencional= np.array([[1,5,6,7], [9,10,15,16]])
print("Shape:", array_multidimencional.shape)
print("Array_unidades:",array_multidimencional )

Shape: (2, 4)
Array_unidades: [[ 1  5  6  7]
 [ 9 10 15 16]]


In [21]:
array_multidimencional[1,3]

16

In [27]:
array_multidimencional[0,0:2]

array([1, 5])

In [31]:
array_multidimencional_random_int = np.random.randint(0,1000, size=(3,4))
print("Shape:", array_multidimencional_random_int.shape)
print("Array_unidades:",array_multidimencional_random_int )

Shape: (3, 4)
Array_unidades: [[464 992 521 595]
 [ 53 520  39 843]
 [840 508 884 316]]


In [33]:
array_3d_random_int = np.random.randint(0,1000, size=(3,4,5))
print("Shape:", array_3d_random_int.shape)
print("Array_unidades:",array_3d_random_int)

Shape: (3, 4, 5)
Array_unidades: [[[699 706 270 410 154]
  [403 116 231 184 310]
  [541 119 750 843  57]
  [545 605   9 645 856]]

 [[681  64 124  31 187]
  [701 230 378 213 519]
  [340 511 778 602 919]
  [901 258 904 260 659]]

 [[590  91 498 244 149]
  [897 510 987 324 505]
  [ 56 469 347  84  15]
  [945 516 370 268 471]]]
